# Generated by Django 5.2.6 on 2025-09-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridal_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='designer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
