# Generated by Django 5.2.6 on 2025-09-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridal_api', '0004_collection_created_at_alter_collection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'dress')},
        ),
    ]
