# Generated by Django 5.2.6 on 2025-09-21 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridal_api', '0005_appointment_status_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualTryOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='user_uploads/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='virtual_tryon_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_tryons', to='bridal_api.dress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_tryons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
