# Generated by Django 5.2.6 on 2025-09-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridal_api', '0008_remove_payment_order_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dress',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
