# Generated by Django 5.2.6 on 2025-09-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridal_api', '0010_category_remove_dress_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('designer', 'Designer')], default='user', max_length=20),
        ),
    ]
